apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: kube-logging
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None # Headless Service
  ports:
    - port: 9200 # Rest API通信
      name: rest
    - port: 9300 # Node 之間通信
      name: inter-node